### ISSUE TITLE
Simple Version for Deployment

### ISSUE THREAD

**Issue by pranjalkar99** [samthakur587/doc_search#1]
It should have simpler code structure and "Dockerfile" named file as needed by cloud run, as well as simpler requirements.txt and better layering structure of Dockerfile for faster and efficient builds.

**Comment by pranjalkar99** [comment]
Refer this : https://github.com/pranjalkar99/grok-langchain-api

**Comment by samthakur587** [comment]
> It should have simpler code structure and "Dockerfile" named file as needed by cloud run, as well as simpler requirements.txt and better layering structure of Dockerfile for faster and efficient builds.

😄
